branch-defaults:
  default:
    artifact: www/Archive.zip
    deploy: null
    environment: uda-api-dev
global:
  application_name: uda-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
